return {
    require('config.plug.autopairs'),
    require('config.plug.bufferline'),
    require('config.plug.cmp'),
    require('config.plug.gitsigns'),
    require('config.plug.lualine'),
    require('config.plug.nvimtree'),
    require('config.plug.telescope'),
    require('config.plug.tabline'),
    require('config.plug.treesitter'),
    require('config.plug.ultisnips'),
    require('config.plug.hop'),
    require('config.plug.which-key'),
    require('config.plug.nvim-comment'),
    require('config.plug.luasnip'),
    require('config.plug.rust-tools'),
}
